CREATE TABLE IF NOT EXISTS `uni1_ships` (
  `ship_id` int(10) unsigned NOT NULL,
  `ship_name` char(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ship_destroyed` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `owner_id`int(10) unsigned NOT NULL,
  `hull` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `engines` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `power` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `computer` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `sensors` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `beams` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `torp_launchers` tinyint(3) NOT NULL DEFAULT '0',
  `torps` bigint(20) NOT NULL DEFAULT '0',
  `shields` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `armor` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `armor_pts` bigint(20) NOT NULL DEFAULT '0',
  `cloak` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `credits` bigint(20) NOT NULL DEFAULT '0',
  `galaxy` int(10) unsigned NOT NULL DEFAULT '0',
  `system` int(10) unsigned NOT NULL DEFAULT '0',
  `ship_ore` bigint(20) NOT NULL DEFAULT '0',
  `ship_organics` bigint(20) NOT NULL DEFAULT '0',
  `ship_goods` bigint(20) NOT NULL DEFAULT '0',
  `ship_energy` bigint(20) NOT NULL DEFAULT '0',
  `ship_colonists` bigint(20) NOT NULL DEFAULT '0',
  `ship_fighters` bigint(20) NOT NULL DEFAULT '0',
  `ship_damage` smallint(5) NOT NULL DEFAULT '0',
  `turns` smallint(4) NOT NULL DEFAULT '0',
  `on_planet` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `dev_warpedit` smallint(5) NOT NULL DEFAULT '0',
  `dev_genesis` smallint(5) NOT NULL DEFAULT '0',
  `dev_beacon` smallint(5) NOT NULL DEFAULT '0',
  `dev_emerwarp` smallint(5) NOT NULL DEFAULT '0',
  `dev_escapepod` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `dev_fuelscoop` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `dev_minedeflector` bigint(20) NOT NULL DEFAULT '0',
  `turns_used` int(10) unsigned NOT NULL DEFAULT '0',
  `last_login` datetime DEFAULT NULL,
  `last_kami` datetime DEFAULT NULL,
  `last_sofa` datetime DEFAULT NULL,
  `ship_kills` int(11) NOT NULL DEFAULT '0',
  `ship_deaths` int(11) NOT NULL DEFAULT '0',
  `rating` int(11) NOT NULL DEFAULT '0',
  `score` int(11) NOT NULL DEFAULT '0',
  `points` int(11) NOT NULL DEFAULT '0',
  `team` int(11) NOT NULL DEFAULT '0',
  `team_invite` int(11) NOT NULL DEFAULT '0',
  `planet_id` int(10) unsigned NOT NULL DEFAULT '0',
  `preset1` int(11) NOT NULL DEFAULT '0',
  `preset2` int(11) NOT NULL DEFAULT '0',
  `preset3` int(11) NOT NULL DEFAULT '0',
  `preset4` int(11) NOT NULL DEFAULT '0',
  `preset5` int(11) NOT NULL DEFAULT '0',
  `trade_colonists` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  `trade_fighters` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `trade_torps` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `trade_energy` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  `cleared_defences` tinytext COLLATE utf8_unicode_ci,
  `dev_lssd` enum('Y','N') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y'
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `uni1_ships` MODIFY `ship_id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;