{block name="title" prepend}Achievements{/block}{block name="content"}
{if $manual_28_step == 0}
<script type="text/javascript">
	$(function() {
		qtips('.ach_head', 'During the game you can do differents achievements. Pick any favorite achievement and begin completing it. As reward, you get  {$LNG.ach_points} and antimatter, how higher the succesfull achievement, how higher the reward.', 'leftMiddle', 'topRight');
setInterval(function() { AJAX() }, 6000)
	});
	</script>
{/if}

<div id="page"><div id="content"><div id="achivment"><div class="ach_main_block"><div class="ach_head"><div class="ach_head_p">{$LNG.ach_prog}</div><div class="ach_head_right"> {$LNG.ach_ach}: <span>460</span></div></div><div class="ach_main_content"><div class="ach_menu"><ul><li class="active"><a href="game.php?page=Achievements&amp;group=general">{$LNG.ach_general}</a></li><li ><a href="game.php?page=Achievements&amp;group=daily">{$LNG.ach_daily}</a></li><li ><a href="game.php?page=Achievements&amp;group=build">{$LNG.alm_buildings}</a></li><li ><a href="game.php?page=Achievements&amp;group=tech">{$LNG.alm_reseach}</a></li><li ><a href="game.php?page=Achievements&amp;group=fleet">{$LNG.alm_fleets}</a></li><li ><a href="game.php?page=Achievements&amp;group=def">{$LNG.alm_defense}</a></li><li ><a href="game.php?page=Achievements&amp;group=varia">Misc</a></li></ul>
</div><div class="ach_content_box"><div style="float:left;width:100%;"><div class="ach_content"><div class="stars_2">{$total_points_attack}</div><div class="ach_next_info tooltip" data-tooltip-content="<span style='color:#F90;font-weight:bold;'> {$LNG.ach_bonus_next}</span><br>&bull;{$next_am_attack} {$LNG.tech.922} <br>&bull;{$next_points_attack} {$LNG.ach_points}">?</div><div class="ach_img"><img alt="" src="styles/images/achiev/ach_wons_day.png" ></div><div class="ach_content_text"><div class="ach_text_head"><span>raider lvl.{$achievements_attack}</span></div><div class="ach_text_boby"><p>{$LNG.ach_daily_1}</p></div><div class="ach_text_need"><p>  {$LNG.ach_perform}<br><span >Win {$achievement_next_require_attack} battle.</span><br></p></div></div><div class="clear"></div></div><div class="ach_content"><div class="stars_2">{$total_points_hostal}</div><div class="ach_next_info tooltip" data-tooltip-content="<span style='color:#F90;font-weight:bold;'> {$LNG.ach_bonus_next}</span><br>&bull;{$next_am_hostal} {$LNG.tech.922} <br>&bull;{$next_points_hostal} {$LNG.ach_points}">?</div><div class="ach_img"><img alt="" src="styles/images/achiev/ach_wons_em_day.png" ></div><div class="ach_content_text"><div class="ach_text_head"><span>hostals victory lvl.{$achievements_hostal}</span></div><div class="ach_text_boby"><p>{$LNG.ach_daily_2}</p></div><div class="ach_text_need"><p>  {$LNG.ach_perform}<br><span >Win {$achievement_next_require_hostal} battle in the Hostal sector.</span><br></p></div></div><div class="clear"></div></div><div class="ach_content"><div class="stars_2">{$total_points_expe}</div><div class="ach_next_info tooltip" data-tooltip-content="<span style='color:#F90;font-weight:bold;'> {$LNG.ach_bonus_next}</span><br>&bull;{$next_am_expe} {$LNG.tech.922} <br>&bull;{$next_points_expe} {$LNG.ach_points}">?</div><div class="ach_img"><img alt="" src="styles/images/achiev/ach_expedition_day.png" ></div><div class="ach_content_text"><div class="ach_text_head"><span>expeditions lvl.{$achievements_expedition}</span></div><div class="ach_text_boby"><p>{$LNG.ach_daily_3}</p></div><div class="ach_text_need"><p>  {$LNG.ach_perform}<br><span >make{$achievement_next_require_expe}successful flights in the expedition.</span><br></p></div></div><div class="clear"></div></div></div><div style="padding-top:7px;"></div><div class="clear"></div></div></div></div></div></div></div><div class="clear"></div></div>{/block}